name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore **/Everything.sln

    - name: Build
      run: dotnet build **/Everything.sln --no-restore

    - name: Test
      run: dotnet test **/Everything.sln --no-build --verbosity normal
